= This is (my) OpenShift Origin on CentOS7
Christoph Görn <goern@redhat.com>
0.1.0, 2016-02-28

== Prerequisites

This demo requires https://vagrantup.com/[Vagrant] and libvirt to be installed.
The Vagrant plugin https://github.com/smdahlen/vagrant-hostmanager[hostmanager]
must be installed too.

10GiB of free RAM and a little bit of disk space should be available.

The host needs to have internet access as it will download RPMs and docker
container images.

== Preparation

`git clone --recursive https://github.com/goern/my-openshift-origin-centos7`

TIP: To let ansible do a smoth job, you might consider `export ANSIBLE_HOST_KEY_CHECKING=False`.

== Configuration

Please have a look at the top of the Vagrantfile, it carries a section you could
use to configure you OpenShift Origin environment:

[source, bash]
----
DEPLOY_CEPH=false
CEPH_MONS=3
CEPH_OSDS=3
DEPLOY_IDM=false
OPENSHIFT_MASTERS=1
OPENSHIFT_NODES=2
OPENSHIFT_NODES_ATOMIC=true
----

== Usage

`vagrant up --no-parallel` will do the trick, let an easy `ansible-playbook --user=vagrant --become --become-user=root --inventory inventory.ini --private-key=~/.vagrant.d/insecure_private_key openshift-ansible/playbooks/byo/config.yml `
follow.

WARNING: This will take about 1.x hrs to finish, given you have a high bandwidth
internet connection and a reasonable fast disk. This is approx. 1 hour for `vagrant up`
and additional 20 minutes per each ansible run.

TIP: If you want to bring down the time vagrant needs to bring up the VM, check
if there are newer box versions, so that yum doesnt have to update that much.

You should now deploy a https://docs.openshift.org/latest/install_config/install/deploy_router.html#creating-the-router-service-account[router] and a registry.

=== OpenShift Origin Web Console

You should be able to access the web console at http://master-0.goern.example.com:8443/
using any user or password. The OpenShift master is configured to do a 'allow_all'
authentication.

== Known Issues

=== dnsIP of Nodes

The configuration item dnsIP is not set on any node, therefor the kubelet is
trying to resolve IP addresses via the host resolver, which is pointing to
the host all the Vagrant VMs run on (aka gateway).

==== workaround

First bring up the master, figure out its IP address and set openshift_dns_ip in
the inventory.ini accordingly.

=== pod node label selector conflicts with its project node label selector

see https://lists.openshift.redhat.com/openshift-archives/users/2016-February/msg00036.html

=== no cluster-admin

As we use the allow_all auth method, there needs to be one cluster admin.

==== workaround

Use `oadm policy add-cluster-role-to-user cluster-admin admin` to assign this
role to the admin user. Use admin as login on the web console.

== References
