= This is (my) OpenShift Origin on CentOS7
Christoph Görn <goern@redhat.com>
0.1.0, 2016-02-28

== Prerequisites

This demo requires https://vagrantup.com/[Vagrant] and libvirt to be installed.
The Vagrant plugin https://github.com/smdahlen/vagrant-hostmanager[hostmanager]
must be installed too.

10GiB of free RAM and a little bit of disk space should be available.

The host needs to have internet access as it will download RPMs and docker
container images.

== Preparation

`git clone --recursive https://github.com/goern/my-openshift-origin-centos7`

== Usage

`vagrant up --no-parallel` will do the trick, let an easy `ansible-playbook -i inventory.ini --private-key=~/.vagrant.d/insecure_private_key openshift-ansible/playbooks/byo/config.yml`
follow.

WARNING: This will take about x hrs to finish, given you have a high bandwidth
internet connection and a reasonable fast disk.

=== OpenShift Origin Web Console

You should be able to access the web console at http://master-1.goern.example.com:8443/
using any user or password. The OpenShift master is configured to do a 'allow_all'
authentication.

== References
